# -*- mode:python -*-

Import('*')

SimObject('L2ToDramSys.py', sim_objects=['L2ToDramSys'])
SimObject('L2L3DramSys.py', sim_objects=['L2L3DramSys'])
SimObject('L2L3DramSysM1Local1Dram.py',
          sim_objects=['L2L3DramSysM1Local1Dram'])

Source('L2todram.cc')
Source('L2L3DramSys.cc')
Source('L2L3DramSysM1Local1Dram.cc')

DebugFlag('CHI')
