Import('*')

# all below tests must add --unit-test to enable unit test mode!
# eg: scons build/RISCV/cpu/pred/btb/test/tage.test.debug --unit-test -j100

# Add the test source files
GTest('uras.test', 'uras_test.cc')

# Add BTB test with minimal dependencies
GTest('btb.test', 
    '../mbtb.cc',
    'btb.test.cc',
    '../timed_base_pred.cc',
)

GTest('abtb.test',
    '../abtb.cc',
    '../mbtb.cc',
    'abtb.test.cc',
    '../timed_base_pred.cc',
)

# Add TAGE test with necessary dependencies
GTest('tage.test', 
    '../btb_tage.cc',
    '../btb_tage_ub.cc',
    'btb_tage.test.cc',
    '../folded_hist.cc',
    '../timed_base_pred.cc',
)

GTest('mgsc.test',
    '../btb_mgsc.cc',
    'btb_mgsc.test.cc',
    '../folded_hist.cc',
    '../timed_base_pred.cc',
)

GTest('llbpx.test',
    '../btb_llbpx.cc',
    '../btb_tage.cc',
    '../btb_tage_ub.cc',
    'btb_llbpx.test.cc',
    '../folded_hist.cc',
    '../timed_base_pred.cc',
)

GTest('folded_hist.test',
    'folded_hist.test.cc',
    '../folded_hist.cc',
)

GTest('history_manager.test',
    'history_manager.test.cc',
)

# add --unit-test to enable unit test mode for RAS
# TODO: Fix RAS test
# GTest('ras.test',
#     'ras_test.cc',
#     '../ras.cc',
#     '../timed_base_pred.cc',
# )

# Add the test to UNITTESTS target
env.Append(UNITTESTS=['uras.test',
        'btb.test',
        'tage.test',
        'mgsc.test',
        'folded_hist.test',
        'history_manager.test',
        'jump_ahead.test',
        'fetch_target_queue.test',
        'decoupled_bpred.test'])
