Import('*')

GTest('bop.test',
    'bop.test.cc',
    'bop.cc',
)

GTest('cmc.test',
    'cmc.test.cc',
    'cmc.cc',
)

# Add the test to UNITTESTS target
env.Append(UNITTESTS=['cmc.test',
                      'bop.test'])