#pragma once
namespace gem5
{
namespace xsCHI
{

    enum class CHI_OP_TYPE
    {
        CHI_REQ_OP_START,
        CHI_REQ_REQLCRDRETURN         ,
        CHI_REQ_READSHARED            ,
        CHI_REQ_READCLEAN             ,
        CHI_REQ_READONCE              ,
        CHI_REQ_READNOSNP             ,//need
        CHI_REQ_PCRDRETURN            ,
        CHI_REQ_READUNIQUE            ,
        CHI_REQ_CLEANSHARED           ,
        CHI_REQ_CLEANINVALID          ,
        CHI_REQ_MAKEINVALID           ,
        CHI_REQ_CLEANUNIQUE           ,
        CHI_REQ_MAKEUNIQUE            ,
        CHI_REQ_EVICT                 ,
        CHI_REQ_EOBARRIER             ,
        CHI_REQ_ECBARRIER             ,
        CHI_REQ_READNOSNPSEP          ,
        CHI_REQ_CLEANSHAREDPERSISTSEP ,
        CHI_REQ_DVMOP                 ,
        CHI_REQ_WRITEEVICTFULL        ,
        CHI_REQ_WRITECLEANFULL        ,
        CHI_REQ_WRITEUNIQUEPTL        ,
        CHI_REQ_WRITEUNIQUEFULL       ,
        CHI_REQ_WRITEBACKPTL          ,
        CHI_REQ_WRITEBACKFULL         ,
        CHI_REQ_WRITENOSNPPTL         ,
        CHI_REQ_WRITENOSNPFULL        ,
        CHI_REQ_WRITEUNIQUEFULLSTASH  ,
        CHI_REQ_WRITEUNIQUEPTLSTASH   ,
        CHI_REQ_STASHONCESHARED       ,
        CHI_REQ_STASHONCEUNIQUE       ,
        CHI_REQ_READONCECLEANINVALID  ,
        CHI_REQ_READONCEMAKEINVALID   ,
        CHI_REQ_READNOTSHAREDDIRTY    ,
        CHI_REQ_CLEANSHAREDPERSIST    ,
        CHI_REQ_ATOMICSTOREADD        ,
        CHI_REQ_ATOMICSTORECLR        ,
        CHI_REQ_ATOMICSTOREEOR        ,
        CHI_REQ_ATOMICSTORESET        ,
        CHI_REQ_ATOMICSTORESMAX       ,
        CHI_REQ_ATOMICSTORESMIN       ,
        CHI_REQ_ATOMICSTOREUMAX       ,
        CHI_REQ_ATOMICSTOREUMIN       ,
        CHI_REQ_ATOMICLOADADD         ,
        CHI_REQ_ATOMICLOADCLR         ,
        CHI_REQ_ATOMICLOADEOR         ,
        CHI_REQ_ATOMICLOADSET         ,
        CHI_REQ_ATOMICLOADSMAX        ,
        CHI_REQ_ATOMICLOADSMIN        ,
        CHI_REQ_ATOMICLOADUMAX        ,
        CHI_REQ_ATOMICLOADUMIN        ,
        CHI_REQ_ATOMICSWAP            ,
        CHI_REQ_ATOMICCOMPARE         ,
        CHI_REQ_PREFETCHTGT           ,
        CHI_REQ_MAKEREADUNIQUE        ,
        CHI_REQ_WRITEEVICTOREVICT     ,
        CHI_REQ_WRITEUNIQUEZERO       ,
        CHI_REQ_WRITENOSNPZERO        ,
        CHI_REQ_WRITENOSNPSEP         ,
        CHI_REQ_STASHONCESEPSHARED    ,
        CHI_REQ_STASHONCESEPUNIQUE    ,
        CHI_REQ_WRITESHAREDCLEANFULL  ,
        CHI_REQ_READSHAREDREJECT      ,
        CHI_REQ_READNSDREJECT         ,
        CHI_REQ_READPREFERUNIQUE      ,
        CHI_REQ_WNSFCLEANSHARED        ,
        CHI_REQ_WNSFCLEANINVALID       ,
        CHI_REQ_WNSFCLEANSHAREDPERSIST ,
        CHI_REQ_WUFCLEANSHARED         ,
        CHI_REQ_WUFCLEANINVALID        ,
        CHI_REQ_WUFCLEANSHAREDPERSIST  ,
        CHI_REQ_WBFCLEANSHARED         ,
        CHI_REQ_WBFCLEANINVALID        ,
        CHI_REQ_WBFCLEANSHAREDPERSIST  ,
        CHI_REQ_WCFCLEANSHARED         ,
        CHI_REQ_WCFCLEANINVALID        ,
        CHI_REQ_WCFCLEANSHAREDPERSIST  ,
        CHI_REQ_WNSPCLEANSHARED        ,
        CHI_REQ_WNSPCLEANINVALID       ,
        CHI_REQ_WNSPCLEANSHAREDPERSIST ,
        CHI_REQ_WUPCLEANSHARED         ,
        CHI_REQ_WUPCLEANSHAREDPERSIST  ,
        CHI_REQ_OP_END,

        CHI_SNP_OP_START,
        CHI_SNP_SNPLCRDRETURN        ,
        CHI_SNP_SNPSHARED            ,
        CHI_SNP_SNPCLEAN             ,
        CHI_SNP_SNPONCE              ,
        CHI_SNP_SNPNOTSHAREDDIRTY    ,
        CHI_SNP_SNPUNIQUESTASH       ,
        CHI_SNP_SNPMAKEINVALIDSTASH  ,
        CHI_SNP_SNPUNIQUE            ,
        CHI_SNP_SNPCLEANSHARED       ,
        CHI_SNP_SNPCLEANINVALID      ,
        CHI_SNP_SNPMAKEINVALID       ,
        CHI_SNP_SNPSTASHUNIQUE       ,
        CHI_SNP_SNPSTASHSHARED       ,
        CHI_SNP_SNPDVMOP             ,
        CHI_SNP_SNPQUERY             ,
        CHI_SNP_SNPSHAREDFWD         ,
        CHI_SNP_SNPCLEANFWD          ,
        CHI_SNP_SNPONCEFWD           ,
        CHI_SNP_SNPNOTSHAREDDIRTYFWD ,
        CHI_SNP_SNPPREFERUNIQUE      ,
        CHI_SNP_SNPPREFERUNIQUEFWD   ,
        CHI_SNP_SNPUNIQUEFWD         ,
        CHI_SNP_OP_END,

        CHI_DAT_OP_START,
        CHI_DAT_DATLCRDRETURN     ,
        CHI_DAT_SNPRESPDATA       ,
        CHI_DAT_COPYBACKWRDATA    ,
        CHI_DAT_NONCOPYBACKWRDATA ,
        CHI_DAT_COMPDATA          ,
        CHI_DAT_SNPRESPDATAPTL    ,
        CHI_DAT_SNPRESPDATAFWDED  ,
        CHI_DAT_WRITEDATACANCEL   ,
        CHI_DAT_DATASEPRESP       ,
        CHI_DAT_NCBWRDATACOMPACK  ,
        CHI_DAT_HNP_RDBURST       ,
        CHI_DAT_OP_END,

        CHI_RSP_OP_START,
        CHI_RSP_RSPLCRDRETURN ,
        CHI_RSP_SNPRESP       ,
        CHI_RSP_COMPACK       ,
        CHI_RSP_RETRYACK      ,
        CHI_RSP_COMP          ,
        CHI_RSP_COMPDBIDRESP  ,
        CHI_RSP_DBIDRESP      ,
        CHI_RSP_PCRDGRANT     ,
        CHI_RSP_READRECEIPT   ,
        CHI_RSP_SNPRESPFWDED  ,
        CHI_RSP_TAGMATCH      ,
        CHI_RSP_RESPSEPDATA   ,
        CHI_RSP_PERSIST       ,
        CHI_RSP_COMPPERSIST   ,
        CHI_RSP_DBIDRESPORD   ,
        CHI_RSP_STASHDONE     ,
        CHI_RSP_COMPSTASHDONE ,
        CHI_RSP_COMPCMO       ,
        CHI_RSP_OP_END,

    };


}}
