#pragma once
#include <string>

namespace gem5
{
namespace xsCHI
{

    enum class CHI_OP_TYPE
    {
        CHI_REQ_OP_START,
        CHI_REQ_REQLCRDRETURN         ,
        CHI_REQ_READSHARED            ,
        CHI_REQ_READCLEAN             ,
        CHI_REQ_READONCE              ,
        CHI_REQ_READNOSNP             ,
        CHI_REQ_PCRDRETURN            ,
        CHI_REQ_READUNIQUE            ,
        CHI_REQ_CLEANSHARED           ,
        CHI_REQ_CLEANINVALID          ,
        CHI_REQ_MAKEINVALID           ,
        CHI_REQ_CLEANUNIQUE           ,
        CHI_REQ_MAKEUNIQUE            ,
        CHI_REQ_EVICT                 ,
        CHI_REQ_EOBARRIER             ,
        CHI_REQ_ECBARRIER             ,
        CHI_REQ_READNOSNPSEP          ,
        CHI_REQ_CLEANSHAREDPERSISTSEP ,
        CHI_REQ_DVMOP                 ,
        CHI_REQ_WRITEEVICTFULL        ,
        CHI_REQ_WRITECLEANFULL        ,
        CHI_REQ_WRITEUNIQUEPTL        ,
        CHI_REQ_WRITEUNIQUEFULL       ,
        CHI_REQ_WRITEBACKPTL          ,
        CHI_REQ_WRITEBACKFULL         ,
        CHI_REQ_WRITENOSNPPTL         ,
        CHI_REQ_WRITENOSNPFULL        ,
        CHI_REQ_WRITEUNIQUEFULLSTASH  ,
        CHI_REQ_WRITEUNIQUEPTLSTASH   ,
        CHI_REQ_STASHONCESHARED       ,
        CHI_REQ_STASHONCEUNIQUE       ,
        CHI_REQ_READONCECLEANINVALID  ,
        CHI_REQ_READONCEMAKEINVALID   ,
        CHI_REQ_READNOTSHAREDDIRTY    ,
        CHI_REQ_CLEANSHAREDPERSIST    ,
        CHI_REQ_ATOMICSTOREADD        ,
        CHI_REQ_ATOMICSTORECLR        ,
        CHI_REQ_ATOMICSTOREEOR        ,
        CHI_REQ_ATOMICSTORESET        ,
        CHI_REQ_ATOMICSTORESMAX       ,
        CHI_REQ_ATOMICSTORESMIN       ,
        CHI_REQ_ATOMICSTOREUMAX       ,
        CHI_REQ_ATOMICSTOREUMIN       ,
        CHI_REQ_ATOMICLOADADD         ,
        CHI_REQ_ATOMICLOADCLR         ,
        CHI_REQ_ATOMICLOADEOR         ,
        CHI_REQ_ATOMICLOADSET         ,
        CHI_REQ_ATOMICLOADSMAX        ,
        CHI_REQ_ATOMICLOADSMIN        ,
        CHI_REQ_ATOMICLOADUMAX        ,
        CHI_REQ_ATOMICLOADUMIN        ,
        CHI_REQ_ATOMICSWAP            ,
        CHI_REQ_ATOMICCOMPARE         ,
        CHI_REQ_PREFETCHTGT           ,
        CHI_REQ_MAKEREADUNIQUE        ,
        CHI_REQ_WRITEEVICTOREVICT     ,
        CHI_REQ_WRITEUNIQUEZERO       ,
        CHI_REQ_WRITENOSNPZERO        ,
        CHI_REQ_WRITENOSNPSEP         ,
        CHI_REQ_STASHONCESEPSHARED    ,
        CHI_REQ_STASHONCESEPUNIQUE    ,
        CHI_REQ_WRITESHAREDCLEANFULL  ,
        CHI_REQ_READSHAREDREJECT      ,
        CHI_REQ_READNSDREJECT         ,
        CHI_REQ_READPREFERUNIQUE      ,
        CHI_REQ_WNSFCLEANSHARED        ,
        CHI_REQ_WNSFCLEANINVALID       ,
        CHI_REQ_WNSFCLEANSHAREDPERSIST ,
        CHI_REQ_WUFCLEANSHARED         ,
        CHI_REQ_WUFCLEANINVALID        ,
        CHI_REQ_WUFCLEANSHAREDPERSIST  ,
        CHI_REQ_WBFCLEANSHARED         ,
        CHI_REQ_WBFCLEANINVALID        ,
        CHI_REQ_WBFCLEANSHAREDPERSIST  ,
        CHI_REQ_WCFCLEANSHARED         ,
        CHI_REQ_WCFCLEANINVALID        ,
        CHI_REQ_WCFCLEANSHAREDPERSIST  ,
        CHI_REQ_WNSPCLEANSHARED        ,
        CHI_REQ_WNSPCLEANINVALID       ,
        CHI_REQ_WNSPCLEANSHAREDPERSIST ,
        CHI_REQ_WUPCLEANSHARED         ,
        CHI_REQ_WUPCLEANSHAREDPERSIST  ,
        CHI_REQ_OP_END,

        CHI_SNP_OP_START,
        CHI_SNP_SNPLCRDRETURN        ,
        CHI_SNP_SNPSHARED            ,
        CHI_SNP_SNPCLEAN             ,
        CHI_SNP_SNPONCE              ,
        CHI_SNP_SNPNOTSHAREDDIRTY    ,
        CHI_SNP_SNPUNIQUESTASH       ,
        CHI_SNP_SNPMAKEINVALIDSTASH  ,
        CHI_SNP_SNPUNIQUE            ,
        CHI_SNP_SNPCLEANSHARED       ,
        CHI_SNP_SNPCLEANINVALID      ,
        CHI_SNP_SNPMAKEINVALID       ,
        CHI_SNP_SNPSTASHUNIQUE       ,
        CHI_SNP_SNPSTASHSHARED       ,
        CHI_SNP_SNPDVMOP             ,
        CHI_SNP_SNPQUERY             ,
        CHI_SNP_SNPSHAREDFWD         ,
        CHI_SNP_SNPCLEANFWD          ,
        CHI_SNP_SNPONCEFWD           ,
        CHI_SNP_SNPNOTSHAREDDIRTYFWD ,
        CHI_SNP_SNPPREFERUNIQUE      ,
        CHI_SNP_SNPPREFERUNIQUEFWD   ,
        CHI_SNP_SNPUNIQUEFWD         ,
        CHI_SNP_OP_END,

        CHI_DAT_OP_START,
        CHI_DAT_DATLCRDRETURN     ,
        CHI_DAT_SNPRESPDATA       ,
        CHI_DAT_COPYBACKWRDATA    ,
        CHI_DAT_NONCOPYBACKWRDATA ,
        CHI_DAT_COMPDATA          ,
        CHI_DAT_SNPRESPDATAPTL    ,
        CHI_DAT_SNPRESPDATAFWDED  ,
        CHI_DAT_WRITEDATACANCEL   ,
        CHI_DAT_DATASEPRESP       ,
        CHI_DAT_NCBWRDATACOMPACK  ,
        CHI_DAT_HNP_RDBURST       ,
        CHI_DAT_OP_END,

        CHI_RSP_OP_START,
        CHI_RSP_RSPLCRDRETURN ,
        CHI_RSP_SNPRESP       ,
        CHI_RSP_COMPACK       ,
        CHI_RSP_RETRYACK      ,
        CHI_RSP_COMP          ,
        CHI_RSP_COMPDBIDRESP  ,
        CHI_RSP_DBIDRESP      ,
        CHI_RSP_PCRDGRANT     ,
        CHI_RSP_READRECEIPT   ,
        CHI_RSP_SNPRESPFWDED  ,
        CHI_RSP_TAGMATCH      ,
        CHI_RSP_RESPSEPDATA   ,
        CHI_RSP_PERSIST       ,
        CHI_RSP_COMPPERSIST   ,
        CHI_RSP_DBIDRESPORD   ,
        CHI_RSP_STASHDONE     ,
        CHI_RSP_COMPSTASHDONE ,
        CHI_RSP_COMPCMO       ,
        CHI_RSP_OP_END,

    };
    class CHI_OP_HELPER
    {
    public:
    static std::string
    CHI_OP_TYPE_TO_STR(CHI_OP_TYPE op) {
        switch (op) {
            case CHI_OP_TYPE::CHI_REQ_OP_START: return "CHI_REQ_OP_START";
            case CHI_OP_TYPE::CHI_REQ_REQLCRDRETURN: return "CHI_REQ_REQLCRDRETURN";
            case CHI_OP_TYPE::CHI_REQ_READSHARED: return "CHI_REQ_READSHARED";
            case CHI_OP_TYPE::CHI_REQ_READCLEAN: return "CHI_REQ_READCLEAN";
            case CHI_OP_TYPE::CHI_REQ_READONCE: return "CHI_REQ_READONCE";
            case CHI_OP_TYPE::CHI_REQ_READNOSNP: return "CHI_REQ_READNOSNP";
            case CHI_OP_TYPE::CHI_REQ_PCRDRETURN: return "CHI_REQ_PCRDRETURN";
            case CHI_OP_TYPE::CHI_REQ_READUNIQUE: return "CHI_REQ_READUNIQUE";
            case CHI_OP_TYPE::CHI_REQ_CLEANSHARED: return "CHI_REQ_CLEANSHARED";
            case CHI_OP_TYPE::CHI_REQ_CLEANINVALID: return "CHI_REQ_CLEANINVALID";
            case CHI_OP_TYPE::CHI_REQ_MAKEINVALID: return "CHI_REQ_MAKEINVALID";
            case CHI_OP_TYPE::CHI_REQ_CLEANUNIQUE: return "CHI_REQ_CLEANUNIQUE";
            case CHI_OP_TYPE::CHI_REQ_MAKEUNIQUE: return "CHI_REQ_MAKEUNIQUE";
            case CHI_OP_TYPE::CHI_REQ_EVICT: return "CHI_REQ_EVICT";
            case CHI_OP_TYPE::CHI_REQ_EOBARRIER: return "CHI_REQ_EOBARRIER";
            case CHI_OP_TYPE::CHI_REQ_ECBARRIER: return "CHI_REQ_ECBARRIER";
            case CHI_OP_TYPE::CHI_REQ_READNOSNPSEP: return "CHI_REQ_READNOSNPSEP";
            case CHI_OP_TYPE::CHI_REQ_CLEANSHAREDPERSISTSEP: return "CHI_REQ_CLEANSHAREDPERSISTSEP";
            case CHI_OP_TYPE::CHI_REQ_DVMOP: return "CHI_REQ_DVMOP";
            case CHI_OP_TYPE::CHI_REQ_WRITEEVICTFULL: return "CHI_REQ_WRITEEVICTFULL";
            case CHI_OP_TYPE::CHI_REQ_WRITECLEANFULL: return "CHI_REQ_WRITECLEANFULL";
            case CHI_OP_TYPE::CHI_REQ_WRITEUNIQUEPTL: return "CHI_REQ_WRITEUNIQUEPTL";
            case CHI_OP_TYPE::CHI_REQ_WRITEUNIQUEFULL: return "CHI_REQ_WRITEUNIQUEFULL";
            case CHI_OP_TYPE::CHI_REQ_WRITEBACKPTL: return "CHI_REQ_WRITEBACKPTL";
            case CHI_OP_TYPE::CHI_REQ_WRITEBACKFULL: return "CHI_REQ_WRITEBACKFULL";
            case CHI_OP_TYPE::CHI_REQ_WRITENOSNPPTL: return "CHI_REQ_WRITENOSNPPTL";
            case CHI_OP_TYPE::CHI_REQ_WRITENOSNPFULL: return "CHI_REQ_WRITENOSNPFULL";
            case CHI_OP_TYPE::CHI_REQ_WRITEUNIQUEFULLSTASH: return "CHI_REQ_WRITEUNIQUEFULLSTASH";
            case CHI_OP_TYPE::CHI_REQ_WRITEUNIQUEPTLSTASH: return "CHI_REQ_WRITEUNIQUEPTLSTASH";
            case CHI_OP_TYPE::CHI_REQ_STASHONCESHARED: return "CHI_REQ_STASHONCESHARED";
            case CHI_OP_TYPE::CHI_REQ_STASHONCEUNIQUE: return "CHI_REQ_STASHONCEUNIQUE";
            case CHI_OP_TYPE::CHI_REQ_READONCECLEANINVALID: return "CHI_REQ_READONCECLEANINVALID";
            case CHI_OP_TYPE::CHI_REQ_READONCEMAKEINVALID: return "CHI_REQ_READONCEMAKEINVALID";
            case CHI_OP_TYPE::CHI_REQ_READNOTSHAREDDIRTY: return "CHI_REQ_READNOTSHAREDDIRTY";
            case CHI_OP_TYPE::CHI_REQ_CLEANSHAREDPERSIST: return "CHI_REQ_CLEANSHAREDPERSIST";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTOREADD: return "CHI_REQ_ATOMICSTOREADD";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTORECLR: return "CHI_REQ_ATOMICSTORECLR";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTOREEOR: return "CHI_REQ_ATOMICSTOREEOR";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTORESET: return "CHI_REQ_ATOMICSTORESET";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTORESMAX: return "CHI_REQ_ATOMICSTORESMAX";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTORESMIN: return "CHI_REQ_ATOMICSTORESMIN";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTOREUMAX: return "CHI_REQ_ATOMICSTOREUMAX";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSTOREUMIN: return "CHI_REQ_ATOMICSTOREUMIN";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADADD: return "CHI_REQ_ATOMICLOADADD";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADCLR: return "CHI_REQ_ATOMICLOADCLR";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADEOR: return "CHI_REQ_ATOMICLOADEOR";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADSET: return "CHI_REQ_ATOMICLOADSET";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADSMAX: return "CHI_REQ_ATOMICLOADSMAX";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADSMIN: return "CHI_REQ_ATOMICLOADSMIN";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADUMAX: return "CHI_REQ_ATOMICLOADUMAX";
            case CHI_OP_TYPE::CHI_REQ_ATOMICLOADUMIN: return "CHI_REQ_ATOMICLOADUMIN";
            case CHI_OP_TYPE::CHI_REQ_ATOMICSWAP: return "CHI_REQ_ATOMICSWAP";
            case CHI_OP_TYPE::CHI_REQ_ATOMICCOMPARE: return "CHI_REQ_ATOMICCOMPARE";
            case CHI_OP_TYPE::CHI_REQ_PREFETCHTGT: return "CHI_REQ_PREFETCHTGT";
            case CHI_OP_TYPE::CHI_REQ_MAKEREADUNIQUE: return "CHI_REQ_MAKEREADUNIQUE";
            case CHI_OP_TYPE::CHI_REQ_WRITEEVICTOREVICT: return "CHI_REQ_WRITEEVICTOREVICT";
            case CHI_OP_TYPE::CHI_REQ_WRITEUNIQUEZERO: return "CHI_REQ_WRITEUNIQUEZERO";
            case CHI_OP_TYPE::CHI_REQ_WRITENOSNPZERO: return "CHI_REQ_WRITENOSNPZERO";
            case CHI_OP_TYPE::CHI_REQ_WRITENOSNPSEP: return "CHI_REQ_WRITENOSNPSEP";
            case CHI_OP_TYPE::CHI_REQ_STASHONCESEPSHARED: return "CHI_REQ_STASHONCESEPSHARED";
            case CHI_OP_TYPE::CHI_REQ_STASHONCESEPUNIQUE: return "CHI_REQ_STASHONCESEPUNIQUE";
            case CHI_OP_TYPE::CHI_REQ_WRITESHAREDCLEANFULL: return "CHI_REQ_WRITESHAREDCLEANFULL";
            case CHI_OP_TYPE::CHI_REQ_READSHAREDREJECT: return "CHI_REQ_READSHAREDREJECT";
            case CHI_OP_TYPE::CHI_REQ_READNSDREJECT: return "CHI_REQ_READNSDREJECT";
            case CHI_OP_TYPE::CHI_REQ_READPREFERUNIQUE: return "CHI_REQ_READPREFERUNIQUE";
            case CHI_OP_TYPE::CHI_REQ_WNSFCLEANSHARED: return "CHI_REQ_WNSFCLEANSHARED";
            case CHI_OP_TYPE::CHI_REQ_WNSFCLEANINVALID: return "CHI_REQ_WNSFCLEANINVALID";
            case CHI_OP_TYPE::CHI_REQ_WNSFCLEANSHAREDPERSIST: return "CHI_REQ_WNSFCLEANSHAREDPERSIST";
            case CHI_OP_TYPE::CHI_REQ_WUFCLEANSHARED: return "CHI_REQ_WUFCLEANSHARED";
            case CHI_OP_TYPE::CHI_REQ_WUFCLEANINVALID: return "CHI_REQ_WUFCLEANINVALID";
            case CHI_OP_TYPE::CHI_REQ_WUFCLEANSHAREDPERSIST: return "CHI_REQ_WUFCLEANSHAREDPERSIST";
            case CHI_OP_TYPE::CHI_REQ_WBFCLEANSHARED: return "CHI_REQ_WBFCLEANSHARED";
            case CHI_OP_TYPE::CHI_REQ_WBFCLEANINVALID: return "CHI_REQ_WBFCLEANINVALID";
            case CHI_OP_TYPE::CHI_REQ_WBFCLEANSHAREDPERSIST: return "CHI_REQ_WBFCLEANSHAREDPERSIST";
            case CHI_OP_TYPE::CHI_REQ_WCFCLEANSHARED: return "CHI_REQ_WCFCLEANSHARED";
            case CHI_OP_TYPE::CHI_REQ_WCFCLEANINVALID: return "CHI_REQ_WCFCLEANINVALID";
            case CHI_OP_TYPE::CHI_REQ_WCFCLEANSHAREDPERSIST: return "CHI_REQ_WCFCLEANSHAREDPERSIST";
            case CHI_OP_TYPE::CHI_REQ_WNSPCLEANSHARED: return "CHI_REQ_WNSPCLEANSHARED";
            case CHI_OP_TYPE::CHI_REQ_WNSPCLEANINVALID: return "CHI_REQ_WNSPCLEANINVALID";
            case CHI_OP_TYPE::CHI_REQ_WNSPCLEANSHAREDPERSIST: return "CHI_REQ_WNSPCLEANSHAREDPERSIST";
            case CHI_OP_TYPE::CHI_REQ_WUPCLEANSHARED: return "CHI_REQ_WUPCLEANSHARED";
            case CHI_OP_TYPE::CHI_REQ_WUPCLEANSHAREDPERSIST: return "CHI_REQ_WUPCLEANSHAREDPERSIST";
            case CHI_OP_TYPE::CHI_REQ_OP_END: return "CHI_REQ_OP_END";
            case CHI_OP_TYPE::CHI_SNP_OP_START: return "CHI_SNP_OP_START";
            case CHI_OP_TYPE::CHI_SNP_SNPLCRDRETURN: return "CHI_SNP_SNPLCRDRETURN";
            case CHI_OP_TYPE::CHI_SNP_SNPSHARED: return "CHI_SNP_SNPSHARED";
            case CHI_OP_TYPE::CHI_SNP_SNPCLEAN: return "CHI_SNP_SNPCLEAN";
            case CHI_OP_TYPE::CHI_SNP_SNPONCE: return "CHI_SNP_SNPONCE";
            case CHI_OP_TYPE::CHI_SNP_SNPNOTSHAREDDIRTY: return "CHI_SNP_SNPNOTSHAREDDIRTY";
            case CHI_OP_TYPE::CHI_SNP_SNPUNIQUESTASH: return "CHI_SNP_SNPUNIQUESTASH";
            case CHI_OP_TYPE::CHI_SNP_SNPMAKEINVALIDSTASH: return "CHI_SNP_SNPMAKEINVALIDSTASH";
            case CHI_OP_TYPE::CHI_SNP_SNPUNIQUE: return "CHI_SNP_SNPUNIQUE";
            case CHI_OP_TYPE::CHI_SNP_SNPCLEANSHARED: return "CHI_SNP_SNPCLEANSHARED";
            case CHI_OP_TYPE::CHI_SNP_SNPCLEANINVALID: return "CHI_SNP_SNPCLEANINVALID";
            case CHI_OP_TYPE::CHI_SNP_SNPMAKEINVALID: return "CHI_SNP_SNPMAKEINVALID";
            case CHI_OP_TYPE::CHI_SNP_SNPSTASHUNIQUE: return "CHI_SNP_SNPSTASHUNIQUE";
            case CHI_OP_TYPE::CHI_SNP_SNPSTASHSHARED: return "CHI_SNP_SNPSTASHSHARED";
            case CHI_OP_TYPE::CHI_SNP_SNPDVMOP: return "CHI_SNP_SNPDVMOP";
            case CHI_OP_TYPE::CHI_SNP_SNPQUERY: return "CHI_SNP_SNPQUERY";
            case CHI_OP_TYPE::CHI_SNP_SNPSHAREDFWD: return "CHI_SNP_SNPSHAREDFWD";
            case CHI_OP_TYPE::CHI_SNP_SNPCLEANFWD: return "CHI_SNP_SNPCLEANFWD";
            case CHI_OP_TYPE::CHI_SNP_SNPONCEFWD: return "CHI_SNP_SNPONCEFWD";
            case CHI_OP_TYPE::CHI_SNP_SNPNOTSHAREDDIRTYFWD: return "CHI_SNP_SNPNOTSHAREDDIRTYFWD";
            case CHI_OP_TYPE::CHI_SNP_SNPPREFERUNIQUE: return "CHI_SNP_SNPPREFERUNIQUE";
            case CHI_OP_TYPE::CHI_SNP_SNPPREFERUNIQUEFWD: return "CHI_SNP_SNPPREFERUNIQUEFWD";
            case CHI_OP_TYPE::CHI_SNP_SNPUNIQUEFWD: return "CHI_SNP_SNPUNIQUEFWD";
            case CHI_OP_TYPE::CHI_SNP_OP_END: return "CHI_SNP_OP_END";
            case CHI_OP_TYPE::CHI_DAT_OP_START: return "CHI_DAT_OP_START";
            case CHI_OP_TYPE::CHI_DAT_DATLCRDRETURN: return "CHI_DAT_DATLCRDRETURN";
            case CHI_OP_TYPE::CHI_DAT_SNPRESPDATA: return "CHI_DAT_SNPRESPDATA";
            case CHI_OP_TYPE::CHI_DAT_COPYBACKWRDATA: return "CHI_DAT_COPYBACKWRDATA";
            case CHI_OP_TYPE::CHI_DAT_NONCOPYBACKWRDATA: return "CHI_DAT_NONCOPYBACKWRDATA";
            case CHI_OP_TYPE::CHI_DAT_COMPDATA: return "CHI_DAT_COMPDATA";
            case CHI_OP_TYPE::CHI_DAT_SNPRESPDATAPTL: return "CHI_DAT_SNPRESPDATAPTL";
            case CHI_OP_TYPE::CHI_DAT_SNPRESPDATAFWDED: return "CHI_DAT_SNPRESPDATAFWDED";
            case CHI_OP_TYPE::CHI_DAT_WRITEDATACANCEL: return "CHI_DAT_WRITEDATACANCEL";
            case CHI_OP_TYPE::CHI_DAT_DATASEPRESP: return "CHI_DAT_DATASEPRESP";
            case CHI_OP_TYPE::CHI_DAT_NCBWRDATACOMPACK: return "CHI_DAT_NCBWRDATACOMPACK";
            case CHI_OP_TYPE::CHI_DAT_HNP_RDBURST: return "CHI_DAT_HNP_RDBURST";
            case CHI_OP_TYPE::CHI_DAT_OP_END: return "CHI_DAT_OP_END";
            case CHI_OP_TYPE::CHI_RSP_OP_START: return "CHI_RSP_OP_START";
            case CHI_OP_TYPE::CHI_RSP_RSPLCRDRETURN: return "CHI_RSP_RSPLCRDRETURN";
            case CHI_OP_TYPE::CHI_RSP_SNPRESP: return "CHI_RSP_SNPRESP";
            case CHI_OP_TYPE::CHI_RSP_COMPACK: return "CHI_RSP_COMPACK";
            case CHI_OP_TYPE::CHI_RSP_RETRYACK: return "CHI_RSP_RETRYACK";
            case CHI_OP_TYPE::CHI_RSP_COMP: return "CHI_RSP_COMP";
            case CHI_OP_TYPE::CHI_RSP_COMPDBIDRESP: return "CHI_RSP_COMPDBIDRESP";
            case CHI_OP_TYPE::CHI_RSP_DBIDRESP: return "CHI_RSP_DBIDRESP";
            case CHI_OP_TYPE::CHI_RSP_PCRDGRANT: return "CHI_RSP_PCRDGRANT";
            case CHI_OP_TYPE::CHI_RSP_READRECEIPT: return "CHI_RSP_READRECEIPT";
            case CHI_OP_TYPE::CHI_RSP_SNPRESPFWDED: return "CHI_RSP_SNPRESPFWDED";
            case CHI_OP_TYPE::CHI_RSP_TAGMATCH: return "CHI_RSP_TAGMATCH";
            case CHI_OP_TYPE::CHI_RSP_RESPSEPDATA: return "CHI_RSP_RESPSEPDATA";
            case CHI_OP_TYPE::CHI_RSP_PERSIST: return "CHI_RSP_PERSIST";
            case CHI_OP_TYPE::CHI_RSP_COMPPERSIST: return "CHI_RSP_COMPPERSIST";
            case CHI_OP_TYPE::CHI_RSP_DBIDRESPORD: return "CHI_RSP_DBIDRESPORD";
            case CHI_OP_TYPE::CHI_RSP_STASHDONE: return "CHI_RSP_STASHDONE";
            case CHI_OP_TYPE::CHI_RSP_COMPSTASHDONE: return "CHI_RSP_COMPSTASHDONE";
            case CHI_OP_TYPE::CHI_RSP_COMPCMO: return "CHI_RSP_COMPCMO";
            case CHI_OP_TYPE::CHI_RSP_OP_END: return "CHI_RSP_OP_END";
            default: return "UNKNOWN_CHI_OP_TYPE";
        }
    }
    };



}}
