Import('*')

SimObject('CacheWrapper.py', sim_objects=[
    'CacheWrapper', 'L2CacheWrapper',
])

Source('CacheWrapper.cc')
Source('L2CacheWrapper.cc')
Source('L2MainPipe.cc')
Source('RequestBuffer.cc')
Source('RequestArbiter.cc')

DebugFlag('CacheWrapper')
DebugFlag('L2CacheWrapper')