# -*- mode:python -*-

Import('*')

DebugFlag('MatrixCuteTrace')

Source('matrix_regfile.cc')
Source('MatrixRegArbiter.cc')
Source('LocalMMU.cc')
Source('MemoryAdapter.cc')
Source('Gem5MemoryAdapter.cc')
Source('TaskController.cc')
Source('CUTETOP.cc')
Source('Scoreboard.cc')
Source('MatrixReg.cc')
Source('MemoryLoader.cc')
Source('MatrixTE.cc')
