# -*- mode:python -*-

# Copyright (c) 2018 Inria
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

SimObject('ReplacementPolicies.py', sim_objects=[
    'BaseReplacementPolicy', 'DuelingRP', 'FIFORP', 'SecondChanceRP',
    'LFURP', 'LRURP', 'BIPRP', 'MRURP', 'RandomRP', 'BRRIPRP', 'SHiPRP',
    'SHiPMemRP', 'SHiPPCRP', 'TreePLRURP', 'WeightedLRURP', 'XSDRRIPRP',
    'SDBPRP'])

Source('bip_rp.cc')
Source('brrip_rp.cc')
Source('dueling_rp.cc')
Source('fifo_rp.cc')
Source('lfu_rp.cc')
Source('lru_rp.cc')
Source('mru_rp.cc')
Source('random_rp.cc')
Source('second_chance_rp.cc')
Source('ship_rp.cc')
Source('sdbp_core.cc')
Source('sdbp_rp.cc')
DebugFlag('SDBP')
Source('tree_plru_rp.cc')
Source('weighted_lru_rp.cc')
Source('xs_drrip_rp.cc')

GTest('replaceable_entry.test', 'replaceable_entry.test.cc')
GTest('sdbp_core.test', 'sdbp_core.test.cc', 'sdbp_core.cc')
GTest('sdbp_rp.test', 'sdbp_rp.test.cc', 'sdbp_core.cc', 'sdbp_rp.cc',
      '../../../base/stats/group.cc', '../../../base/stats/info.cc',
      '../../../base/stats/storage.cc', '../../../base/statistics.cc',
      '../../../base/time.cc', '../../../base/hostinfo.cc',
      '../../../base/output.cc', '../../../sim/core.cc',
      '../../../sim/sim_object.cc', '../../../sim/globals.cc',
      '../../../sim/tags.cc', '../../../sim/root.cc',
      '../../../sim/probe/probe.cc', '../../../sim/port.cc',
      '../../../sim/bufval.cc', '../../packet.cc',
      with_any_tags('gem5 trace', 'gem5 events',
                    'gem5 drain', 'gem5 serialize'))
