# -*- mode:python -*-

Import('*')

SimObject('CHIBridge.py', sim_objects=['CHIBridge'])
SimObject('FakeL3.py', sim_objects=['FakeL3'])
SimObject('L2Wrapper.py', sim_objects=['L2Wrapper'])
if env['HAVE_DRAMSIM3']:
    SimObject('DDRWrapper.py', sim_objects=['DDRWrapper'])
Source('CHIBridge.cc')
Source('DDRWrapper.cc')
Source('fakeL3.cc')
Source('L2Wrapper.cc')

DebugFlag('CHIBridge')
DebugFlag('CHIDramsim')
DebugFlag('CHIL2Wrapper')