# -*- mode:python -*-

Import('*')

SimObject('CHIBridge.py', sim_objects=['CHIBridge'])
SimObject('FakeL3.py', sim_objects=['FakeL3'])
SimObject('CHI_L2.py', sim_objects=['CHI_L2'])
SimObject('MeshNode.py', sim_objects=['MeshNode'])
SimObject('CHI_L3.py', sim_objects=['CHI_L3'])
if env['HAVE_DRAMSIM3']:
    SimObject('DDRWrapper.py', sim_objects=['DDRWrapper'])
Source('CHIBridge.cc')
Source('DDRWrapper.cc')
Source('fakeL3.cc')
Source('CHI_L2.cc')
Source('MeshNode.cc')
Source('CHI_L3.cc')

DebugFlag('CHIBridge')
DebugFlag('CHIDramsim')
DebugFlag('CHIL2Wrapper')
DebugFlag('CHIFakeL3')
DebugFlag('CHIMeshNode')

DebugFlag('CHIL3')
DebugFlag('CHIL3Txn')