Import('*')

SimObject('ValuePredictor.py',
          sim_objects=[
            'ValuePredictor',
            'CVPArb',
            'CVPFixedPriorityArb',
            'CVPRandomArb',
            'CVPRRArb',
            'CVPConfidenceArb',
            'EStride',
            'VTAGE',
            'ExampleValuePredictor',
            'CompositeValuePredictor',
            'MemoryRenaming',
            'IdealConstantLVP',
            'EgDiff'
          ],
          enums=['ValuePredType'])

Source('valuepred_unit.cc')
Source('composite_value_predictor_arb.cc')
Source('composite_value_predictor.cc')
Source('enhanced_stride.cc')
Source('vtage.cc')
Source('example_value_predictor.cc')
Source('memory_renaming.cc')
Source('ideal_constant_lvp.cc')
Source('egdiff.cc')

DebugFlag('VPCOMMON')
DebugFlag('EStride')
DebugFlag('VTAGE')
DebugFlag('MemoryRenaming')
DebugFlag('EgDiff')


CompoundFlag('VP', ['VPCOMMON', 'EStride', 'VTAGE', 'MemoryRenaming',
                    'EgDiff'])
