Import('*')

SimObject('CacheWrapper.py', sim_objects=[
    'CacheWrapper', 'L3CacheSlice', 'L3CacheWrapper'
])

Source('CacheWrapper.cc')
Source('L3CacheSlice.cc')
Source('L3CacheWrapper.cc')
Source('L3MainPipe.cc')
Source('RequestBuffer.cc')
Source('RequestArbiter.cc')
Source('SlicedCacheAccessor.cc')

DebugFlag('CacheWrapper')
DebugFlag('L3CacheSlice')
DebugFlag('L3CacheWrapper')
DebugFlag('L3MainPipe')