name: gem5 SMT SPEC2006 Performance Test(0.3c)

on:
  schedule:
    # Run every Tuesday at 23:59 UTC+8 (15:59 UTC)
    - cron: '59 15 * * 2'
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  perf_test:
    if: |
      github.event_name != 'pull_request_target' ||
      (github.event.label.name == 'perf-smt' &&
       github.event.pull_request.base.ref == 'xs-dev' &&
       github.event.pull_request.head.repo.full_name == github.repository)
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/smt_idealkmhv3.py
      benchmark_type: "gcc12-spec06-smt-0.3c"
      distributed_servers: "default"
      distributed_jobs_per_server: 32
      pr_sha: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
