name: gem5 Ideal BTB Weekly Performance Test

on:
  schedule:
    # Run every Thursday at 23:59 UTC+8 (15:59 UTC)
    - cron: '59 15 * * 4'
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  align_test_spec06:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/kmhv3.py
      benchmark_type: "gcc15-spec06-1.0c"

  align_test_spec17:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/kmhv3.py
      benchmark_type: "spec17-1.0c"

  perf_test_spec06:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/idealkmhv3.py
      benchmark_type: "gcc15-spec06-1.0c"

  perf_test_spec17:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/idealkmhv3.py
      benchmark_type: "spec17-1.0c"

  smt_test_spec06:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/smt_idealkmhv3.py
      benchmark_type: "gcc12-spec06-smt-1.0c"
      distributed_servers: "default"
      distributed_jobs_per_server: 32
      check_result: false
      timeout_minutes: 720
