name: gem5 Ideal BTB Performance Test (no SC) (Tier 2 - Post-Merge)

on:
  # only can be triggered manually
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to test (leave empty for current branch)'
        required: false
        type: string

jobs:
  perf_test:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      script_path: ../kmh_v3_btb_nosc.sh
      benchmark_type: "spec06-0.8c"