name: gem5 Ideal BTB Performance Test (1Taken)

on:
  push:
    branches: [ 2-taken-v8-upperbound ]


jobs:
  perf_test:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      script_path: ../kmh_v3_btb_1taken.sh
      benchmark_type: "spec06-0.8c"