name: gem5 Simple RVV Performance Test (Ideal BTB)

on:
  workflow_dispatch:

jobs:
  perf_test:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/idealkmhv3.py
      benchmark_type: "spec06int-rvv-0.8c"
      vector_type: "simple"
      gcbv_ref_so: /nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-interpreter-so
      check_result: false # Warning: rvv test will not show the difftest failure
