name: gem5 Vector Test (Tier 2 - Post-Merge)

on:
  push:
    branches: [ xs-dev ]
  # Removed pull_request trigger
  workflow_dispatch:

jobs:
  vector-test:
    runs-on: node
    continue-on-error: false
    name: XS-GEM5 - Running vector test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-dramsim
      - name: Build GEM5 opt
        run: |
          CC=gcc CXX=g++ scons build/RISCV/gem5.opt --linker=gold -j64 --rvv-impl=simple
      - name: run vector test
        run: parallux .github/workflows/gem5_vec.py
