name: gem5 Align BTB Performance Test(0.3c)

on:
  push:
    branches: [ xs-dev, '*-align' ]  # xs-dev for normal CI, *-align for BTB-only performance testing (align to RTL)
  # Removed pull_request trigger, only can be triggered use *-align branches

  workflow_dispatch:

jobs:
  perf_test:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      config_path: configs/example/kmhv3.py
      extra_args: "--btb-tage-upper-bound"
      benchmark_type: "gcc15-spec06-0.3c"
